import React, { useState, useRef, useEffect } from 'react';
import {
  RefreshCcw,
  Skull,
  Camera,
  XCircle,
  BarChart3,
  Sparkles,
  BrainCircuit,
  Trash2,
  Frown,
  AlertTriangle,
  Radiation
} from 'lucide-react';
import { CHARACTERS, RESPONSES, FOLLOW_UP } from './constants';
import { generateRoast, generateDeepRoast } from './services/geminiService';
import { Character, FollowUpType } from './types';

export default function DarkRoastBook() {
  const [step, setStep] = useState<'welcome' | 'select' | 'input' | 'loading' | 'result' | 'followup'>('welcome');
  const [selectedChar, setSelectedChar] = useState<string | null>(null);
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [loadingMsg, setLoadingMsg] = useState('');
  const [followUpType, setFollowUpType] = useState<FollowUpType | null>(null);
  const [followUpText, setFollowUpText] = useState('');
  const [misfortuneLevel, setMisfortuneLevel] = useState(0);
  const [isScreenshotMode, setIsScreenshotMode] = useState(false);
  const [isAiGenerating, setIsAiGenerating] = useState(false);

  // New States for Deep Roast
  const [deepRoastResult, setDeepRoastResult] = useState('');
  const [isDeepRoasting, setIsDeepRoasting] = useState(false);
  const [showDeepRoast, setShowDeepRoast] = useState(false);

  const timerRef = useRef<number | null>(null);

  // 產生主要解答 (Gemini > Fallback)
  const handleGenerateAnswer = async () => {
    if (!selectedChar) return;
    setStep('loading');
    setIsAiGenerating(true);

    const charData = CHARACTERS.find(c => c.id === selectedChar);
    if (!charData) return;

    // Loading Animation Text
    let msgIdx = 0;
    if (timerRef.current) clearInterval(timerRef.current);
    
    setLoadingMsg(charData.loadingText[0]);
    timerRef.current = window.setInterval(() => {
      msgIdx++;
      setLoadingMsg(charData.loadingText[msgIdx % charData.loadingText.length]);
    }, 800);

    // Call API
    const aiResponse = await generateRoast(charData.systemPrompt, question);

    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
    setIsAiGenerating(false);

    if (aiResponse) {
      setAnswer(aiResponse);
    } else {
      // Fallback
      let category: keyof typeof RESPONSES['dad'] = 'default';
      const q = question.toLowerCase();
      if (q.includes('工作') || q.includes('離職') || q.includes('老闆') || q.includes('錢') || q.includes('累')) category = 'work';
      if (q.includes('愛') || q.includes('男友') || q.includes('女友') || q.includes('結婚') || q.includes('性')) category = 'love';
      
      const charResponses = RESPONSES[selectedChar];
      // Type assertion needed because dynamic access logic is tricky with TS
      const options = (charResponses && charResponses[category]) ? charResponses[category] : charResponses['default'];
      setAnswer(options[Math.floor(Math.random() * options.length)]);
    }

    setMisfortuneLevel(Math.floor(Math.random() * 40) + 60);
    setStep('result');
  };

  // 深度靈魂拷問 (Deep Roast)
  const handleDeepRoast = async () => {
    if (!selectedChar) return;
    setIsDeepRoasting(true);
    const charData = CHARACTERS.find(c => c.id === selectedChar);

    if (charData) {
        const aiResponse = await generateDeepRoast(charData.desc, question);
        setDeepRoastResult(aiResponse || "AI 拒絕分析你的靈魂，可能是因為你太無趣了，或者是免費 API 額度用完了。");
    }
    
    setIsDeepRoasting(false);
    setShowDeepRoast(true);
  };

  const handleFollowUp = (type: FollowUpType) => {
    if (!selectedChar) return;
    setFollowUpType(type);
    setFollowUpText(FOLLOW_UP[selectedChar][type]);
    setStep('followup');
  };

  const reset = () => {
    setStep('select');
    setQuestion('');
    setAnswer('');
    setFollowUpType(null);
    setFollowUpText('');
    setIsScreenshotMode(false);
    setDeepRoastResult('');
    setShowDeepRoast(false);
  };

  const currentChar = CHARACTERS.find(c => c.id === selectedChar);

  const getMisfortuneColor = (level: number) => 
    level < 70 ? 'text-yellow-600' : level < 90 ? 'text-orange-600' : 'text-red-600 animate-pulse';

  return (
    <div className={`min-h-screen bg-[#FFD90F] font-sans text-black selection:bg-black selection:text-[#FFD90F] flex flex-col items-center justify-center p-4 overflow-hidden relative font-comic ${isScreenshotMode ? 'pt-20' : ''}`}>
      
      {/* Background Noise */}
      <div 
        className="absolute top-0 left-0 w-full h-full opacity-10 pointer-events-none z-0"
        style={{
          backgroundImage: 'radial-gradient(#000 1px, transparent 1px)',
          backgroundSize: '15px 15px'
        }}
      />

      {isScreenshotMode && (
        <div className="absolute bottom-4 right-4 text-xs font-black opacity-50 z-20">
          GENERATED BY 暗黑解答之書
        </div>
      )}

      {/* Main Container */}
      <div className={`w-full max-w-2xl z-10 relative transition-all duration-500 ${isScreenshotMode ? 'scale-95' : ''}`}>
        
        {/* Header */}
        {!isScreenshotMode ? (
          <div className="mb-8 text-center transform -rotate-1">
            <h1 
              className="text-5xl md:text-7xl font-black uppercase tracking-tighter drop-shadow-[5px_5px_0px_rgba(0,0,0,1)] text-white stroke-black"
              style={{
                textShadow: '4px 4px 0px #000, -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000',
                fontFamily: '"Arial Black", "Impact", sans-serif'
              }}
            >
              社畜<br/>嘲諷指南
            </h1>
            <div className="mt-4 inline-flex items-center gap-2 bg-black text-white px-4 py-1 transform rotate-2 border-2 border-white">
              <Sparkles size={16} className="text-yellow-300" />
              <span className="font-bold tracking-widest text-sm">POWERED BY GEMINI</span>
            </div>
          </div>
        ) : (
          <div className="mb-6 text-center">
            <div className="inline-block bg-black text-[#FFD90F] px-4 py-2 font-black text-2xl border-4 border-white transform -rotate-2">
              ⚠️ 社畜嘲諷指南
            </div>
          </div>
        )}

        {/* Card Area */}
        <div className={`bg-white border-[6px] border-black shadow-[10px_10px_0px_0px_rgba(0,0,0,1)] p-6 md:p-8 min-h-[450px] flex flex-col justify-center relative rounded-lg ${isScreenshotMode ? 'shadow-none border-8' : ''}`}>
          
          {/* Screenshot Toggle */}
          {(step === 'result' || step === 'followup') && !isScreenshotMode && (
            <button 
              onClick={() => setIsScreenshotMode(true)} 
              className="absolute top-4 right-4 p-2 bg-gray-100 hover:bg-black hover:text-white border-2 border-black rounded-full transition-colors z-20"
              title="開啟截圖模式"
            >
              <Camera size={20} />
            </button>
          )}
          {isScreenshotMode && (
            <button 
              onClick={() => setIsScreenshotMode(false)} 
              className="absolute top-4 right-4 p-2 bg-red-500 text-white border-2 border-black rounded-full transition-colors z-20 hover:scale-110"
              title="關閉截圖模式"
            >
              <XCircle size={24} />
            </button>
          )}

          {/* STEP 0: Welcome */}
          {step === 'welcome' && (
            <div className="text-center space-y-6 animate-fade-in">
              <div className="flex justify-center mb-4 relative">
                <Skull size={90} className="animate-bounce text-black" strokeWidth={2.5} />
                <div className="absolute top-0 right-1/3 text-red-600 animate-ping opacity-75">
                  <Radiation size={40} />
                </div>
              </div>
              <h2 className="text-3xl font-black transform -skew-x-6">生活爛透了嗎？</h2>
              <p className="text-lg font-bold border-l-4 border-black pl-4 text-left bg-gray-100 p-2">
                這裡沒有雞湯，只有砒霜。<br/>
                我們連線了最毒舌的 AI 導師 (Gemini)，<br/>
                準備好讓他們用最惡毒的實話摧毀你。
              </p>
              <button 
                onClick={() => setStep('select')} 
                className="w-full mt-4 bg-[#FFD90F] border-4 border-black text-2xl font-black py-4 hover:bg-black hover:text-[#FFD90F] transition-all shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none active:translate-x-[6px] active:translate-y-[6px]"
              >
                按下這裡毀滅人生
              </button>
            </div>
          )}

          {/* STEP 1: Select */}
          {step === 'select' && (
            <div className="space-y-6 animate-fade-in">
              <h2 className="text-2xl font-black text-center mb-6 bg-black text-white py-2 transform skew-x-[-5deg]">誰來羞辱你？</h2>
              <div className="grid grid-cols-1 gap-4">
                {CHARACTERS.map((char) => (
                  <button 
                    key={char.id} 
                    onClick={() => { setSelectedChar(char.id); setStep('input'); }}
                    className={`group relative p-4 border-4 border-black text-left transition-all hover:-translate-y-1 hover:shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] flex items-center gap-4 ${char.color}`}
                  >
                    <div className="bg-white border-2 border-black p-2 rounded-full shrink-0">
                      {char.icon}
                    </div>
                    <div>
                      <h3 className="text-xl font-black uppercase flex items-center gap-2">
                        {char.name}
                        <span className="text-xs bg-black text-white px-2 py-0.5 rounded-full font-normal opacity-0 group-hover:opacity-100 transition-opacity">
                          {char.subtitle}
                        </span>
                      </h3>
                      <p className="text-xs font-bold opacity-80 mt-1">{char.desc}</p>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* STEP 2: Input */}
          {step === 'input' && currentChar && (
            <div className="space-y-6 animate-fade-in">
              <div className={`flex items-center space-x-4 border-b-4 border-black pb-4 ${currentChar.color} p-4 -mx-6 -mt-6 mb-4 border-b-black`}>
                <div className="bg-white p-2 border-2 border-black rounded-full">
                  {currentChar.icon}
                </div>
                <div>
                  <h3 className="font-black text-xl">{currentChar.name}</h3>
                  <p className="text-sm font-bold opacity-70">"{currentChar.quote}"</p>
                </div>
              </div>

              <div className="relative">
                <textarea 
                  value={question} 
                  onChange={(e) => setQuestion(e.target.value)}
                  placeholder="輸入你那毫無意義的煩惱... 例如：我該約炮嗎？我還是處男嗎？"
                  className="w-full h-36 p-4 border-4 border-black text-xl font-bold placeholder:text-gray-400 focus:outline-none focus:bg-gray-50 resize-none font-mono"
                />
                <div className="absolute bottom-4 right-4 pointer-events-none opacity-20">
                  <Trash2 size={40} />
                </div>
              </div>

              <div className="flex justify-between items-center gap-4">
                <button 
                  onClick={() => setStep('select')} 
                  className="font-bold underline hover:bg-black hover:text-white px-2 py-1"
                >
                  ← 換個人
                </button>
                <button 
                  onClick={handleGenerateAnswer} 
                  disabled={!question.trim()}
                  className="flex-1 bg-red-600 text-white text-xl font-black py-3 border-4 border-black hover:bg-red-700 disabled:opacity-50 disabled:bg-gray-400 transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-[2px_2px_0px_0px_rgba(0,0,0,1)] hover:translate-x-[2px] hover:translate-y-[2px]"
                >
                  {isAiGenerating ? 'AI 構思中...' : '尋求羞辱'}
                </button>
              </div>
            </div>
          )}

          {/* STEP 3: Loading */}
          {step === 'loading' && currentChar && (
            <div className="flex flex-col items-center justify-center space-y-8 py-10">
              <div className="relative">
                <div className="animate-spin-slow text-black">
                  <RefreshCcw size={80} strokeWidth={1} />
                </div>
                <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 animate-bounce">
                  {currentChar.icon}
                </div>
              </div>
              <h3 className="text-2xl font-black bg-black text-white px-6 py-3 transform -rotate-2 shadow-[4px_4px_0px_0px_#888]">
                {loadingMsg}
              </h3>
              <div className="text-sm font-bold animate-pulse text-gray-500">
                Gemini AI 正在編寫惡毒笑話...
              </div>
            </div>
          )}

          {/* STEP 4 & 5: Result & Interaction */}
          {(step === 'result' || step === 'followup') && currentChar && (
            <div className="space-y-6 animate-fade-in flex flex-col h-full items-center">
              <div className="text-center opacity-60 text-sm font-bold mb-2 w-full truncate px-4">
                問題：{question}
              </div>

              <div className="flex justify-center -mb-8 z-10">
                <div className={`p-4 rounded-full border-4 border-black bg-white shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]`}>
                  {currentChar.icon}
                </div>
              </div>

              <div className={`relative w-full p-8 pt-10 border-4 border-black ${currentChar.color} shadow-[8px_8px_0px_0px_rgba(0,0,0,1)] transform rotate-1 mb-2`}>
                <h2 className="text-2xl md:text-3xl font-black leading-tight text-center drop-shadow-sm">
                  "{answer}"
                </h2>
                <div className="absolute -top-3 -left-3 bg-black text-white px-3 py-1 text-sm font-bold border-2 border-white transform -rotate-3">
                  WARNING: TRUTH
                </div>
              </div>

              {/* Misfortune Meter */}
              {!showDeepRoast && (
                <div className="w-full bg-gray-100 border-4 border-black p-4 mb-2 relative overflow-hidden">
                  <div className="flex justify-between items-end mb-2 relative z-10">
                    <div className="flex items-center gap-2">
                      <BarChart3 size={24} />
                      <span className="font-black text-lg uppercase">今日厄運指數</span>
                    </div>
                    <span className={`text-3xl font-black ${getMisfortuneColor(misfortuneLevel)}`}>
                      {misfortuneLevel}%
                    </span>
                  </div>
                  <div className="w-full h-6 bg-white border-2 border-black rounded-full overflow-hidden relative">
                    <div 
                      className={`h-full transition-all duration-1000 ease-out ${misfortuneLevel > 80 ? 'bg-red-600' : 'bg-yellow-400'}`}
                      style={{ width: `${misfortuneLevel}%` }}
                    />
                  </div>
                </div>
              )}

              {/* Gemini Feature: Deep Roast Button */}
              {step === 'result' && !showDeepRoast && !isScreenshotMode && (
                <button
                  onClick={handleDeepRoast}
                  disabled={isDeepRoasting}
                  className="w-full bg-indigo-600 text-white border-4 border-black py-3 font-black text-lg hover:bg-indigo-700 transition-all flex items-center justify-center gap-2 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none hover:translate-x-[2px] hover:translate-y-[2px]"
                >
                  {isDeepRoasting ? (
                    <RefreshCcw className="animate-spin" />
                  ) : (
                    <Sparkles className="animate-pulse text-yellow-300" />
                  )}
                  {isDeepRoasting ? 'Gemini 正在深入你的黑暗面...' : ' ✨ 深度靈魂拷問 (AI 長篇分析)'}
                </button>
              )}

              {/* Deep Roast Result Box */}
              {showDeepRoast && (
                <div className="w-full animate-slide-up relative mt-4">
                  <div className="bg-indigo-900 border-4 border-black p-6 text-white shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]">
                    <div className="flex items-center gap-2 mb-4 border-b-2 border-indigo-700 pb-2">
                      <BrainCircuit className="text-pink-400" />
                      <h3 className="font-bold text-pink-400 uppercase tracking-widest">Psychological Damage Report</h3>
                    </div>
                    <p className="font-bold text-lg leading-relaxed whitespace-pre-line">{deepRoastResult}</p>
                  </div>
                </div>
              )}

              {/* Interaction Buttons */}
              {step === 'result' && !showDeepRoast && !isScreenshotMode && (
                <div className="grid grid-cols-2 gap-4 w-full mt-2">
                  <button 
                    onClick={() => handleFollowUp('submit')} 
                    className="flex flex-col items-center justify-center p-4 border-4 border-black bg-white hover:bg-gray-200 transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
                  >
                    <Frown size={32} className="mb-2" />
                    <span className="font-black text-lg">我是廢物...</span>
                  </button>
                  <button 
                    onClick={() => handleFollowUp('rebel')} 
                    className="flex flex-col items-center justify-center p-4 border-4 border-black bg-white hover:bg-red-600 hover:text-white transition-all shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
                  >
                    <AlertTriangle size={32} className="mb-2" />
                    <span className="font-black text-lg">你供三小？</span>
                  </button>
                </div>
              )}

              {/* Follow Up Response */}
              {step === 'followup' && (
                <div className="w-full animate-slide-up mt-4">
                  <div className={`p-6 border-4 border-black text-white font-bold text-xl relative shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] ${followUpType === 'rebel' ? 'bg-red-600' : 'bg-blue-900'}`}>
                    <div className="absolute -top-4 -right-2 bg-yellow-400 text-black text-xs border-2 border-black px-2 py-1 font-black transform rotate-6">
                      CRITICAL HIT!
                    </div>
                    <p>"{followUpText}"</p>
                  </div>
                  {!isScreenshotMode && (
                    <button 
                      onClick={reset} 
                      className="w-full mt-8 bg-white border-4 border-black py-3 font-black text-xl hover:bg-black hover:text-[#FFD90F] transition-all flex items-center justify-center gap-2 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
                    >
                      <RefreshCcw size={20} /> 再來一次 (M屬性爆發)
                    </button>
                  )}
                </div>
              )}

              {/* Reset button for Deep Roast view */}
              {showDeepRoast && !isScreenshotMode && (
                <button 
                  onClick={reset} 
                  className="w-full mt-6 bg-white border-4 border-black py-3 font-black text-xl hover:bg-black hover:text-[#FFD90F] transition-all flex items-center justify-center gap-2 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]"
                >
                  <RefreshCcw size={20} /> 我已經身心受創了 (重來)
                </button>
              )}
            </div>
          )}
        </div>

        {!isScreenshotMode && (
          <div className="mt-8 text-center">
            <p className="text-xs font-bold uppercase tracking-widest opacity-50">© 2025 Springfield Dark Arts</p>
          </div>
        )}
      </div>
    </div>
  );
}